### ISSUE TITLE
RSS link of the death

### ISSUE THREAD

**Issue by tbarbugli** [GetStream/Winds#183]
Links inside articles are opened on the Winds app instead of browser, there is no way for the user to go back to the app (other than quit and reopen it).

**Comment by nparsons08** [comment]
Fixed

**Comment by tschellenbach** [comment]
Actually there were some edge cases were this wasn't fixed. Today's release will solve this.
